### ISSUE TITLE
Unknown column 'order_date' in the field list

### ISSUE THREAD

**Issue by trangntt-016** [gavinklfong/stream-api-exercises#1]
Hi, 

Thank you for your exercises. It's really a great source to learn functional programming and streams. However, I found a small bug and would be happy if you could fix it.

When I tried to run the given SQL scripts, it gave the error "Unknown column 'order_date' in the field list". Probably because in your  class Order, you didn't give a column name (@Column (name="order_date")) so Hibernate generates orderDate in the database. Maybe you can change it to orderDate. Similar things with delivery_date => deliveryDate.

**Comment by gavinklfong** [comment]
@trangntt-016 Thanks a lot for your comments. I fixed the issues by adding annotation @column to the model class. Feel free to let me know if you have any other suggestions.
