### ISSUE TITLE
Clarify usage of Lombok

### ISSUE THREAD

**Issue by s-lindenau** [gavinklfong/stream-api-exercises#7]
A suggestion to improve the readme.md perhaps; clarify that this project requires a Lombok plugin in your IDE if you want to work with the sources directly.

Otherwise this could confuse users: https://stackoverflow.com/questions/72131339/eclipse-maven-build-succeeds-but-project-still-reports-compilation-errors

You could link to https://projectlombok.org/setup/overview for example.

**Comment by gavinklfong** [comment]
@s-lindenau Thanks for your suggestion. I've added a new section to the readme about the IDE setup for Lombok. Thanks.
